version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: forum-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: forum
      MYSQL_USER: forumuser
      MYSQL_PASSWORD: forumpass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    container_name: forum-adminer
    restart: always
    ports:
      - "8080:8080"

  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: forum-nuxt
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DATABASE_HOST: mysql
      DATABASE_USER: forumuser
      DATABASE_PASSWORD: forumpass
      DATABASE_NAME: forum
    command: ["node", ".output/server/index.mjs"]

volumes:
  mysql_data:
